// playground/vue3/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { ContextMenu, MenuGroup, MenuItem, useContextMenu } from '@contextmenu/vue'
import Menu from './components/Menu.vue'
const menuRef = ref<HTMLElement>()
const targetRef = ref<HTMLElement>()

const hideOnClick = ref(true)

const ctx = useContextMenu(menuRef, {
  target: targetRef,
  hideOnClick,
})

// eslint-disable-next-line no-console
const log = console.log
</script>

<template>
  <Menu ref="menuRef">
    [🚀]
  </Menu>
  <div
    ref="targetRef"
    class="w-20 h-20 bg-green"
  >
    TARGET
  </div>
  <!-- <ContextMenu
    :hide-on-click="true"
    @context-menu="log($event.target)"
  >
    <Menu>
      [✈️]
    </Menu>
  </ContextMenu> -->

  <ContextMenu>
    <MenuGroup bg-cyan rounded>
      <MenuItem>Item 1</MenuItem>
      <MenuItem>Item 2</MenuItem>
      <MenuItem>
        SubMenu
        <MenuGroup>
          <MenuItem>Nested1</MenuItem>
          <MenuItem>Nested2</MenuItem>
          <MenuItem>
            SubMenu
            <MenuGroup>
              <MenuItem>Apple</MenuItem>
              <MenuItem>Orange</MenuItem>
              <MenuItem>Banana</MenuItem>
            </MenuGroup>
          </MenuItem>
        </MenuGroup>
      </MenuItem>
    </MenuGroup>
  </ContextMenu>
</template>

<style scoped>
</style>

// playground/react/src/App.tsx
import { ContextMenu, useContextMenu } from '@contextmenu/react'
import React, { forwardRef, useCallback, useRef, useState } from 'react'
import './App.css'

const BooleanString = ({ value }: { value: boolean }) => {
  return (
    <span style={{
      color: value ? 'green' : 'orange',
    }}>{JSON.stringify(value)}</span>
  )
}

const Menu = React.memo(
  forwardRef<HTMLDivElement>(
    (_props, ref) => {
      return (
    <div className="menu" ref={ref}>
      <div>Item 1</div>
      <div>Item 2</div>
      <div>Item 3</div>
    </div>
      )
    },
  ),
)

Menu.displayName = 'MenuX'

function App() {
  const [hideOnClick, setHideOnClick] = useState(false)

  const menu = useRef<HTMLDivElement>(null)
  const target = useRef<HTMLDivElement>(null)

  const onContextMenu = useCallback((e: MouseEvent) => {
    // eslint-disable-next-line no-console
    console.log(e.target)
  }, [])

  const ctx = useContextMenu(menu, {
    hideOnClick,
    target,
    onContextMenu,
  })
  return (
    <div>
      <Menu ref={menu} />
      <div className="target" ref={target}>
        <h3>target</h3>
      </div>
      <div>
        <p>visible: <BooleanString value={ctx.visible} /></p>
        <p>enabled: <BooleanString value={ctx.enabled} /></p>
      </div>
      <button
      onClick={() => setHideOnClick(pre => !pre)}>
        <span>hideOnClick {'=>'} </span>
        <BooleanString value={hideOnClick} />
        </button>
      <ContextMenu
      onContextMenu={onContextMenu}
      hideOnClick={hideOnClick}>
        <div>OK!</div>
      </ContextMenu>
    </div>
  )
}

export default App
